---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node2pod
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node2pod
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
    verbs:
      - get
      - watch
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node2pod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node2pod
subjects:
  - kind: ServiceAccount
    name: node2pod
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node2pod
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: node2pod
  template:
    metadata:
      labels:
        app: node2pod
    spec:
      containers:
        - command:
            - /bin/node2pod
            - --label=topology.kubernetes.io/region
            - --label=topology.kubernetes.io/zone
          image: quay.io/wish/node2pod:main
          name: node2pod
      priorityClassName: system-node-critical
      serviceAccountName: node2pod